//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionshipWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class championshipEntities : DbContext
    {
        public championshipEntities()
            : base("name=championshipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<championship> championships { get; set; }
        public virtual DbSet<city> citys { get; set; }
        public virtual DbSet<coach> coaches { get; set; }
        public virtual DbSet<game_state> game_state { get; set; }
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<judge> judges { get; set; }
        public virtual DbSet<player_state> player_state { get; set; }
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<stage> stages { get; set; }
        public virtual DbSet<statistic> statistics { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<teams_in_stage> teams_in_stage { get; set; }
        public virtual DbSet<type_of_stage> type_of_stage { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
