//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionshipWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public player()
        {
            this.statistics = new HashSet<statistic>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> team_id { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> position_id { get; set; }
        public string photo_path { get; set; }
        public int player_state_id { get; set; }
    
        public virtual player_state player_state { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<statistic> statistics { get; set; }
        public virtual position position { get; set; }
        public virtual team team { get; set; }
    }
}
