//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionshipWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teams_in_stage
    {
        public int teams_id { get; set; }
        public int stage_id { get; set; }
        public Nullable<int> teamscore { get; set; }
    
        public virtual stage stage { get; set; }
        public virtual team team { get; set; }
    }
}
